## Programming Paradigms

**Procedural Programming**
- Code as a sequence of steps
- Ideal for analyzing data (statistical analysis)

**Object Oriented Programming (OOP)**
- Code as a collection and interaction of **objects**
- ideal for building versatile and reusable tools/frameworks

In [1]:
# procedural programming with numpy example
import numpy as np

# step 1
a = np.array([4, 5])

# step 2
b = np.sum(a)

# step 3
print(b)

9


### What is an object?
- An object is a data structure incorporating information about **state** (how the object looks or what properties it has) and **behavior** (what the object does or how to operate on)

In [4]:
import numpy as np

A = np.array([[1, 2],
              [4, 5],
              [2, 5]])

print(A)

print(f"\n the state of A is {A.shape}") # state
print(f"\n the behavior of A is {A.reshape(2, 3)}") # behavior 

[[1 2]
 [4 5]
 [2 5]]

 the state of A is (3, 2)

 the behavior of A is [[1 2 4]
 [5 2 5]]


**Encapsulation:** Bundling of states and behaviors  

More common names in Python:

**State** $\rightarrow$ **Attribute** $\rightarrow$ **Variable**

**Behavior** $\rightarrow$ **Method** $\rightarrow$ **Function**

## What is a Class?

A **Class** is a blueprint or tempalte of object outlining possible states and behaviors

Let's create a class in Python:

### Constructors
- **Constructor** `__init__()` method is called every time an object is created

In [7]:
class Customer:
    def set_name(self, new_name): # "self" represents the object itself
        self.name = new_name

    def display_name(self): # pass the self argument
        print("Name: " + self.name)

# one object or realization of Customer class
c1 = Customer()
c1.set_name("Alex")
c1.display_name()

# another object or realization of Customer class
c2 = Customer()
c2.set_name("Ana")
c2.display_name()

Name: Alex
Name: Ana


### Constructors
- **Constructor** `__init__()` method is called every time an object is created

In [12]:
class Customer:
    # Constructor
    def __init__(self, new_name):
        self.name = new_name

    def display_name(self):
        print("Name: " + self.name)

### Inheritance
- When a class derives from another class (Parent or base $\rightarrow$ Child or subclass)
- Sharing attributes and methods

In [ ]:
class Customer:

    def __init__(self, new_name, discount=0):
        self.name = new_name
        self.discount = discount

    def display_name(self):
        print("Name: " + self.name)

    def give_discount(self, amount):
        self.discount += amount

class VIPCustomer(Customer):  # Inheritance
    
    def __init__(self, new_name, discount=0):
        super(VIPCustomer, self).__init__(new_name, discount) # call the constructor of the parent class

    def give_special_discount(self, amount):
        self.discount += 2 * amount


c2 = VIPCustomer("Ana")
print("Initial Amount", c2.discount)

c2.give_discount(5)
print("Updated Amount", c2.discount) # inherited from parent customer class

c2.give_special_discount(5)
print("Updated Amount with Special Discount", c2.discount)

Initial Amount 0
Updated Amount with Special Discount 10


### Building neural nets in PyTorch
- Define your neural network by **subclassing** from `torch.nn.Module`

- when you define your network you don't have to define parameters as these are already inherited from the base class. 
- you do have to define the `forward` model: which essentially says (in this case) 

        If i have an input `x`, what this model wants to do with `x`. 

In [18]:
import torch
from torch import nn
device = "cuda" if torch.cuda.is_available() else "cpu"

class NeuralNetwork(nn.Module):
    def __init__(self):
        super(NeuralNetwork, self).__init__()
        self.flatten = nn.Flatten()
        self.linear_relu_stack = nn.Sequential(
            nn.Linear(28 * 28, 512),
            nn.ReLU(),
            nn.Linear(512, 512),
            nn.ReLU(),
            nn.Linear(512, 10),
        )
    def forward(self, x):
        x = self.flatten(x)
        logits = self.linear_relu_stack(x)
        return logits

### Building Neural Nets in PyTorch
- We create an **instance** of this subclass and print its structure

In [28]:
model = NeuralNetwork().to(device)
print(model)

NeuralNetwork(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (linear_relu_stack): Sequential(
    (0): Linear(in_features=784, out_features=512, bias=True)
    (1): ReLU()
    (2): Linear(in_features=512, out_features=512, bias=True)
    (3): ReLU()
    (4): Linear(in_features=512, out_features=10, bias=True)
  )
)


Note that model parametesr are already initialized due to inheritance:

In [34]:
X = torch.rand(1, 28, 28, device=device) #number of samples, height, width
logits = model(X)
print(logits)
pred_probab = nn.Softmax(dim=1)(logits)
print(pred_probab)

tensor([[ 0.0316, -0.1063,  0.0364, -0.0254,  0.0097,  0.0078,  0.0349, -0.0336,
         -0.0430,  0.1199]], device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([[0.1027, 0.0895, 0.1032, 0.0970, 0.1005, 0.1003, 0.1030, 0.0962, 0.0953,
         0.1122]], device='cuda:0', grad_fn=<SoftmaxBackward0>)


Attributes for this instance/model

In [37]:
for name, param in model.named_parameters():
    print(f"Layer: {name} | Size: {param.size()}")

Layer: linear_relu_stack.0.weight | Size: torch.Size([512, 784])
Layer: linear_relu_stack.0.bias | Size: torch.Size([512])
Layer: linear_relu_stack.2.weight | Size: torch.Size([512, 512])
Layer: linear_relu_stack.2.bias | Size: torch.Size([512])
Layer: linear_relu_stack.4.weight | Size: torch.Size([10, 512])
Layer: linear_relu_stack.4.bias | Size: torch.Size([10])
